apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-store
spec:
  storageClassName: {{ .Values.storage.className }}
  accessModes: 
  - ReadWriteOnce
  resources: 
    requests:
      storage: {{ .Values.storage.capacity }}