apiVersion: v1
kind: Service
metadata:
  name: simple-upload-server
spec:
  type: NodePort
  selector:
    app: simple-upload-server
  ports:
  - name: http
    protocol: TCP
    port: 25478
    targetPort: http-server
    nodePort: 30080